### ISSUE TITLE
Push code to Github

### ISSUE THREAD

**Issue by diocas** [swan-cern/swan-charts#4]
Let's move the development to Github to allow future collaborations.

**Comment by ebocchi** [comment]
[GitLab swank8s](https://gitlab.cern.ch/swan/k8s/swank8s) is mirrored (push) to [GitHub swan-cern/swan-charts](https://github.com/swan-cern/swan-charts)
- [GitLab swank8s](https://gitlab.cern.ch/swan/k8s/swank8s) should be removed to avoid confusion. Please review!
- All existng branches (on GitLab) are mirrored to GitHub with history
- [GitHub swan-cern/swan-charts](https://github.com/swan-cern/swan-charts) has an additional 'swan-charts' branch with developments for charts management

[GitHub swan-cern/swan-charts] is mirrored back to [GitLab swan-charts](https://gitlab.cern.ch/swan/swan-charts/) to trigger pipelines on CERN's GitLab CI:
- Automated push of charts to Harbor

**Comment by diocas** [comment]
I'm closing this task since Enrico did what was asked in it (feel free to re-open it).
The old repo can be kept for now but should not be used... This means we need to change the k8s bastion puppet config to use this repo instead. @rccern I leave that to you.
