### ISSUE TITLE
Umbrella chart

### ISSUE THREAD

**Issue by diocas** [swan-cern/swan-charts#8]
Create the `swan` chart that automatically installs EOS and CVMFS.
Set values.yaml with the default options.

**Comment by ebocchi** [comment]
Preliminary umbrella chart at https://github.com/swan-cern/swan-charts/tree/swan-charts/swan
- This is mostly a placeholder and to be used as casting stone for further development
- It allows for the selection of the desired EOS/CVMFS client (ours, csi driver) via booleans
- Other values to be added when we will have a (relatively) stable swank8s chart
